image: node:10.6.0

before_script:
  - export NVM_DIR="$HOME/.nvm"
  - . ${NVM_DIR}/nvm.sh
  - nvm install --lts
  - nvm use --lts

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build

unit test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - dist/
      - node_modules/
      - package.json
