import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon'
import 'vue-awesome/icons/pencil-alt'
import 'vue-awesome/icons/times'
import 'vue-awesome/icons/check'
import 'vue-awesome/icons/euro-sign'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/sliders-h'
import 'vue-awesome/icons/list-ol'
import 'vue-awesome/icons/save'
import 'vue-awesome/icons/window-close'
import 'vue-awesome/icons/sort-amount-up-alt'
import 'vue-awesome/icons/sort-amount-down-alt'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/tools'
import 'vue-awesome/icons/arrow-left'
import 'vue-awesome/icons/not-equal'
import 'vue-awesome/icons/equals'
import 'vue-awesome/icons/less-than'
import 'vue-awesome/icons/less-than-equal'
import 'vue-awesome/icons/greater-than'
import 'vue-awesome/icons/greater-than-equal'

Vue.component('VIcon', Icon)
